[project]
timeout = 30

[[tests]]
name = "to_upper_1"
input = ["./to_upper", "foobar"]
expected = """
C: FOOBAR
Asm: FOOBAR
"""
case_sensitive = true
rubric = 10

[[tests]]
name = "to_upper_2"
input = ["./to_upper", "FooBar1{}"]
expected = """
C: FOOBAR1{}
Asm: FOOBAR1{}
"""
case_sensitive = true
rubric = 10

[[tests]]
name = "swap_1"
input = ["./swap", "0", "1", "22", "33"]
expected = """
C: 33 22
Asm: 33 22
"""
rubric = 10

[[tests]]
name = "swap_2"
input = ["./swap", "4", "3", "11", "22", "33", "55", "66", "77"]
expected = """
C: 11 22 33 66 55 77
Asm: 11 22 33 66 55 77
"""
rubric = 10

[[tests]]
name = "fmi_1"
input = ["./find_max_index", "3", "2", "1"]
expected = """
C: 0
Asm: 0
"""
rubric = 10

[[tests]]
name = "fmi_2"
input = ["./find_max_index", "1", "2", "3"]
expected = """
C: 2
Asm: 2
"""
rubric = 10

[[tests]]
name = "sort_1"
input = ["./sort", "1", "2", "3"]
expected = """
C: 3 2 1
Asm: 3 2 1
"""
rubric = 10

[[tests]]
name = "sort_2"
input = ["./sort", "2", "7", "4", "1"]
expected = """
C: 7 4 2 1
Asm: 7 4 2 1
"""
rubric = 10

