[project]
timeout = 30
due_date = "2025-02-25 23:59:59 -0800"

[[tests]]
name = "pack_bytes_1"
input = ["./pack_bytes", "1", "2", "3", "4"]
expected = """
C: 16909060
Asm: 16909060
"""
rubric = 5

[[tests]]
name = "pack_bytes_2"
input = ["./pack_bytes", "255", "255", "255", "255"]
expected = """
C: -1
Asm: -1
"""
rubric = 5

[[tests]]
name = "unpack_bytes_1"
input = ["./unpack_bytes", "16909060"]
expected = """
C: 1 2 3 4
Asm: 1 2 3 4
"""
rubric = 5

[[tests]]
name = "unpack_bytes_2"
input = ["./unpack_bytes", "-2"]
expected = """
C: 255 255 255 254
Asm: 255 255 255 254
"""
rubric = 5

[[tests]]
name = "get_bitseq_1"
input = ["./get_bitseq", "94116", "12", "15"]
expected = """
C: 6
Asm: 6
"""
rubric = 1

[[tests]]
name = "get_bitseq_2"
input = ["./get_bitseq", "94117", "4", "7"]
expected = """
C: 10
Asm: 10
"""
rubric = 1

[[tests]]
name = "get_bitseq_signed_1"
input = ["./get_bitseq_signed", "94117", "12", "15"]
expected = """
C: 6
Asm: 6
"""
rubric = 9

[[tests]]
name = "get_bitseq_signed_2"
input = ["./get_bitseq_signed", "94117", "4", "7"]
expected = """
C: -6
Asm: -6
"""
rubric = 9

[[tests]]
name = "int_to_str1"
input = ["./int_to_str", "2", "-o", "2"]
expected = """
C: 0b10
Asm: 0b10
"""
rubric = 10

[[tests]]
name = "int_to_str2"
input = ["./int_to_str", "0x32", "-o", "10"]
expected = """
C: 50
Asm: 50
"""
rubric = 10

[[tests]]
name = "str_to_int1"
input = ["./str_to_int", "0xffFF", "-o", "10"]
expected = """
C: 65535
Asm: 65535
"""
rubric = 10

[[tests]]
name = "str_to_int2"
input = ["./str_to_int", "0b11111111", "-o", "10"]
expected = """
C: 255
Asm: 255
"""
rubric = 10

